# Generated by Django 4.1 on 2024-10-02 17:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('describtion', models.CharField(default='', max_length=128)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('place', models.CharField(default='', max_length=129)),
                ('entry', models.BooleanField(default=False)),
                ('entry2', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now)),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.event')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
