# Generated by Django 4.1 on 2024-10-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventType',
            field=models.ManyToManyField(to='viewer.eventtype'),
        ),
    ]
