# Generated by Django 4.1 on 2024-09-26 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzivatel', models.CharField(default='', max_length=128)),
                ('comment', models.TextField(default='')),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now)),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.event')),
            ],
        ),
    ]
