# Generated by Django 4.1 on 2024-10-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
