# Generated by Django 4.1 on 2024-10-01 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uzivatel',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='describtion',
            field=models.CharField(default='', max_length=128),
        ),
    ]
