# Generated by Django 4.1 on 2024-10-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_event_eventtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='entry2',
        ),
    ]
