# Generated by Django 4.1.1 on 2024-09-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_event_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry',
            field=models.BooleanField(default=True),
        ),
    ]
