# Generated by Django 4.1 on 2024-10-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_event_image_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='describtion',
            field=models.CharField(default='', max_length=6000),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
