# Generated by Django 4.1.1 on 2024-09-30 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
