# Generated by Django 4.1 on 2024-10-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_event_capacity_event_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
