# Generated by Django 4.1.1 on 2024-10-01 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_remove_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 1)),
        ),
    ]
