# Generated by Django 4.1.1 on 2024-10-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
    ]
