# Generated by Django 4.1.1 on 2024-10-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_remove_event_date_remove_event_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
