# Generated by Django 4.1.1 on 2024-10-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_event_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='place',
            new_name='misto',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='nazev',
        ),
    ]
