# Generated by Django 4.1.1 on 2024-10-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_rename_name_eventtype_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vstupne',
            field=models.BooleanField(default=True),
        ),
    ]
