# Generated by Django 4.1.1 on 2024-10-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_event_datum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='vstupne',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='nazev',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='eventtype',
            old_name='typ',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='event',
            name='misto',
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='', max_length=128),
        ),
    ]
