# Generated by Django 4.1.1 on 2024-10-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_rename_vstupne_event_entry_rename_nazev_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='entry',
            field=models.BooleanField(default=False),
        ),
    ]
