# Generated by Django 4.1.1 on 2024-10-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
