# Generated by Django 4.1 on 2024-10-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_remove_comment_uzivatel_comment_user_and_more'),
        ('viewer', '0021_event_date'),
    ]

    operations = [
    ]
